/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-09-28 09:35:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bank;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class clientRegiste_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<!-- 可选的 Bootstrap 主题文件（一般不用引入） -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->\n");
      out.write("<script src=\"https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>用户开户</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<form action=\"/TELLER2.0/OpenAcc\" method=\"post\">\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th height=\"25\" colspan=\"2\" align=\"left\" bgcolor=\"#006633\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"bg_tr\">\n");
      out.write("\t\t\t\t\t\t\t开户\n");
      out.write("\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\n");
      out.write("\t\t\t\t\t\t\t客户编号：\n");
      out.write("\t\t\t\t\t\t\t");
int num=(int)(Math.random()*10000000);
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<label for=\"disabledTextInput\">\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"CLIENT_NO\" type=\"text\" size=\"40\"\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=");
      out.print(num );
      out.write(" />\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\n");
      out.write("\t\t\t\t\t\t\t国籍：\n");
      out.write("\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"country\" id=\"client_no\" type=\"text\" size=\"40\"\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"38\" onblur=\"getClient(this.value);\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.country}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\n");
      out.write("\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t客户类型：\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"CLIENT_TYPE\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"COM\" selected=\"selected\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t普通客户\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"VIP\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\tVIP客户\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"INT\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t银行员工\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"46\">\n");
      out.write("\t\t\t\t\t\t\t证件号码：\n");
      out.write("\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"GLOBAL_ID\" id=\"global_id\" type=\"text\" size=\"38\"\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"38\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.GLOBAL_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\n");
      out.write("\t\t\t\t\t\t\t证件类型：\n");
      out.write("\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"GLOBAL_ID_TYPE\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"identity_card\" selected=\"selected\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t身份证\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"military_card\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t军人证\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"passport\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t护照\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"must\">*</a>\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\n");
      out.write("\t\t\t\t\t\t\t用户名：\n");
      out.write("\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"name\" type=\"text\" size=\"40\" maxlength=\"40\"/>\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\n");
      out.write("\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t客户分类类型：\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"FM_CLIENT_TYPE\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\" selected=\"selected\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t存款\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t贷款\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\n");
      out.write("\t\t\t\t\t\t\t电话：\n");
      out.write("\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"CLIENT_TEL\" type=\"text\" size=\"40\" maxlength=\"40\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.CLIENT_TEL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\n");
      out.write("\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t性别：\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"sex\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\" selected=\"selected\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t男\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t女\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\n");
      out.write("\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\n");
      out.write("\t\t\t\t\t\t\t地址：\n");
      out.write("\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"LOCATION\" type=\"text\" size=\"40\" maxlength=\"40\"\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.LOCATION}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<input  class=\"class=\"btn btn-default\"\" type=\"submit\"  name=\"submit\"   value=\"提交\"/>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
