/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-09-28 09:50:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bank;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CRM_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<!-- 可选的 Bootstrap 主题文件（一般不用引入） -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->\n");
      out.write("<script src=\"https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("﻿<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\n");
      out.write("    <tbody>\n");
      out.write("    \t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th height=\"25\" colspan=\"8\" align=\"left\" bgcolor=\"#006633\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"bg_tr\">\n");
      out.write("\t\t\t\t\t\t\t客户关系管理\n");
      out.write("\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("        <tr class=\"firstRow\">\n");
      out.write("            <td width=\"170\" valign=\"top\" style=\"word-break: break-all;\" height=\"0\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">客户名称：<span style=\"font-size: 14px; background-color: rgb(128, 100, 162);\"></span></span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" height=\"0\" width=\"128\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"神州数码\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\" orgfontsize=\"\" orgheight=\"\"/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" height=\"0\" width=\"169\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">主联系人：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" height=\"0\" width=\"109\">\n");
      out.write("                <strong><input name=\"leipiNewField\" type=\"text\" title=\"主联系人\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"100\" orgtype=\"text\" style=\"text-align: left; width: 100px;\" orgfontsize=\"\" orgheight=\"\"/></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" height=\"0\" width=\"75\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">移动电话：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" height=\"0\" width=\"117\">\n");
      out.write("                <strong><input name=\"leipiNewField\" type=\"text\" title=\"移动电话\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"100\" orgtype=\"text\" style=\"text-align: left; width: 100px;\" orgfontsize=\"\" orgheight=\"\"/></strong>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"170\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">助记码：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"128\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"助记码\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"169\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">国家/地区：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"109\">\n");
      out.write("                <strong><span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"国家/地区\" leipiplugins=\"select\" size=\"1\" orgwidth=\"100\" style=\"width: 100px;\"><option value=\"中国\" selected=\"selected\">\n");
      out.write("                    中国\n");
      out.write("                </option>\n");
      out.write("                <option value=\"美国\">\n");
      out.write("                    美国\n");
      out.write("                </option>\n");
      out.write("                <option value=\"英国\">\n");
      out.write("                    英国\n");
      out.write("                </option>\n");
      out.write("                <option value=\"法国\">\n");
      out.write("                    法国\n");
      out.write("                </option>\n");
      out.write("                <option value=\"日本\">\n");
      out.write("                    日本\n");
      out.write("                </option></select></span><span leipiplugins=\"select\">&nbsp;&nbsp;</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"89\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">国际区号：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"117\">\n");
      out.write("                <strong><input name=\"leipiNewField\" type=\"text\" title=\"国际区号\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"100\" orgtype=\"text\" style=\"text-align: left; width: 100px;\" orgfontsize=\"\" orgheight=\"\"/></strong>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"170\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">省份：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"128\">\n");
      out.write("                <span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"省份\" leipiplugins=\"select\" size=\"1\" orgwidth=\"120\" style=\"width: 120px;\"><option value=\"陕西\">\n");
      out.write("                    陕西\n");
      out.write("                </option>\n");
      out.write("                <option value=\"广东\">\n");
      out.write("                    广东\n");
      out.write("                </option>\n");
      out.write("                <option value=\"云南\">\n");
      out.write("                    云南\n");
      out.write("                </option>\n");
      out.write("                <option value=\"四川\">\n");
      out.write("                    四川\n");
      out.write("                </option>\n");
      out.write("                <option value=\"浙江\">\n");
      out.write("                    浙江\n");
      out.write("                </option></select>&nbsp;&nbsp;</span>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"169\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">城市：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"109\">\n");
      out.write("                <strong><span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"城市\" leipiplugins=\"select\" size=\"1\" orgwidth=\"100\" style=\"width: 100px;\"><option value=\"西安\" selected=\"selected\">\n");
      out.write("                    西安\n");
      out.write("                </option>\n");
      out.write("                <option value=\"昆明\">\n");
      out.write("                    昆明\n");
      out.write("                </option>\n");
      out.write("                <option value=\"成都\">\n");
      out.write("                    成都\n");
      out.write("                </option>\n");
      out.write("                <option value=\"杭州\">\n");
      out.write("                    杭州\n");
      out.write("                </option>\n");
      out.write("                <option value=\"广州\">\n");
      out.write("                    广州\n");
      out.write("                </option></select></span><span leipiplugins=\"select\">&nbsp;&nbsp;</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"89\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">区号：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"117\">\n");
      out.write("                <strong><input name=\"leipiNewField\" type=\"text\" title=\"区号\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"100\" orgtype=\"text\" style=\"text-align: left; width: 100px;\" orgfontsize=\"\" orgheight=\"\"/></strong>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"170\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">邮编：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"128\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"邮编\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"169\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">详细地址：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"5\" width=\"372\">\n");
      out.write("                <strong><input name=\"leipiNewField\" type=\"text\" title=\"详细地址\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"360\" orgtype=\"text\" style=\"text-align: left; width: 360px;\" orgfontsize=\"\" orgheight=\"\"/></strong>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"170\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">电话：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"128\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"ԅ(¯﹃¯ԅ)\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"169\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">传真：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"109\">\n");
      out.write("                <strong><input name=\"leipiNewField\" type=\"text\" title=\"传真\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"89\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">电子邮件</span>：</strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"117\">\n");
      out.write("                <strong><input name=\"leipiNewField\" type=\"text\" title=\"电子邮件\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/></strong>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"97\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">公司名称：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"128\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"公司名称\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"143\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">公司网址：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"5\" width=\"372\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"公司网址\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"360\" orgtype=\"text\" style=\"text-align: left; width: 360px;\" orgfontsize=\"\" orgheight=\"\"/>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"170\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">所属行业：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"128\">\n");
      out.write("                <strong><span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"所属行业\" leipiplugins=\"select\" size=\"1\" orgwidth=\"120\" style=\"width: 120px;\"><option value=\"软件行业\" selected=\"selected\">\n");
      out.write("                    软件行业\n");
      out.write("                </option>\n");
      out.write("                <option value=\"制造行业\">\n");
      out.write("                    制造行业\n");
      out.write("                </option>\n");
      out.write("                <option value=\"IT行业\">\n");
      out.write("                    IT行业\n");
      out.write("                </option>\n");
      out.write("                <option value=\"销售行业\">\n");
      out.write("                    销售行业\n");
      out.write("                </option></select></span><span leipiplugins=\"select\">&nbsp;&nbsp;</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"97\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">企业性质：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"5\" width=\"372\">\n");
      out.write("                <strong><span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"公司性质\" leipiplugins=\"select\" size=\"1\" orgwidth=\"350\" style=\"width: 350px;\"><option value=\"国企\">\n");
      out.write("                    国企\n");
      out.write("                </option>\n");
      out.write("                <option value=\"民营\">\n");
      out.write("                    民营\n");
      out.write("                </option>\n");
      out.write("                <option value=\"私营\">\n");
      out.write("                    私营\n");
      out.write("                </option></select></span><span leipiplugins=\"select\">&nbsp;&nbsp;</span></strong>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"170\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">客户来源：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"128\">\n");
      out.write("                <strong><span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"客户来源\" leipiplugins=\"select\" size=\"1\" orgwidth=\"120\" style=\"width: 120px;\"><option value=\"电话\">\n");
      out.write("                    电话\n");
      out.write("                </option>\n");
      out.write("                <option value=\"展会\">\n");
      out.write("                    展会\n");
      out.write("                </option>\n");
      out.write("                <option value=\"介绍\">\n");
      out.write("                    介绍\n");
      out.write("                </option>\n");
      out.write("                <option value=\"广告\">\n");
      out.write("                    广告\n");
      out.write("                </option></select></span><span leipiplugins=\"select\">&nbsp;&nbsp;</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"114\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">客户状态：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"5\" width=\"372\">\n");
      out.write("                <strong><span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"客户状态\" leipiplugins=\"select\" size=\"1\" orgwidth=\"350\" style=\"width: 350px;\"><option value=\"有兴趣\">\n");
      out.write("                    有兴趣\n");
      out.write("                </option>\n");
      out.write("                <option value=\"考虑中\">\n");
      out.write("                    考虑中\n");
      out.write("                </option>\n");
      out.write("                <option value=\"暂时不买\">\n");
      out.write("                    暂时不买\n");
      out.write("                </option>\n");
      out.write("                <option value=\"肯定不买\">\n");
      out.write("                    肯定不买\n");
      out.write("                </option></select></span><span leipiplugins=\"select\">&nbsp;&nbsp;</span></strong>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"83\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">开户银行：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"128\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"开户银行\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"169\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">银行账号：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"5\" width=\"372\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"银行账号\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"360\" orgtype=\"text\" style=\"text-align: left; width: 360px;\" orgfontsize=\"\" orgheight=\"\"/>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"161\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">发展阶段：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"128\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"发展阶段\" leipiplugins=\"select\" size=\"1\" orgwidth=\"120\" style=\"width: 120px;\"><option value=\"考察期\">\n");
      out.write("                    考察期\n");
      out.write("                </option>\n");
      out.write("                <option value=\"形成期\">\n");
      out.write("                    形成期\n");
      out.write("                </option>\n");
      out.write("                <option value=\"稳定期\">\n");
      out.write("                    稳定期\n");
      out.write("                </option>\n");
      out.write("                <option value=\"退化期\">\n");
      out.write("                    退化期\n");
      out.write("                </option></select></span><span leipiplugins=\"select\">&nbsp;&nbsp;</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"150\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">客户重要程度</span>：</strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"5\" width=\"372\">\n");
      out.write("                <strong><span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"客户重要程度\" leipiplugins=\"select\" size=\"1\" orgwidth=\"350\" style=\"width: 350px;\"><option value=\"一般\">\n");
      out.write("                    一般\n");
      out.write("                </option>\n");
      out.write("                <option value=\"重要\">\n");
      out.write("                    重要\n");
      out.write("                </option>\n");
      out.write("                <option value=\"很重要\">\n");
      out.write("                    很重要\n");
      out.write("                </option></select></span><span leipiplugins=\"select\">&nbsp;&nbsp;</span></strong>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("    </tbody>\n");
      out.write("</table>\n");
      out.write("<table data-sort=\"sortDisabled\">\n");
      out.write("    <tbody>\n");
      out.write("        <tr class=\"firstRow\">\n");
      out.write("            <td width=\"138\" valign=\"top\" style=\"word-break: break-all;\" height=\"0\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">下次联系日期：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" height=\"0\" width=\"130\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"下次联系日期\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" rowspan=\"1\" colspan=\"1\" height=\"0\" width=\"89\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">联系内容：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td rowspan=\"1\" valign=\"top\" align=\"null\" style=\"word-break: break-all;\" colspan=\"5\" width=\"353\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"联系内容\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"350\" orgtype=\"text\" style=\"text-align: left; width: 350px;\"/>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"158\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">合同到期时间：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"8\" width=\"583\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"合同到期时间\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"610\" orgtype=\"text\" style=\"text-align: left; width: 610px;\" orgfontsize=\"\" orgheight=\"\"/>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"200\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">企业规模：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"93\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"企业规模\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" style=\"word-break: break-all;\" width=\"89\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">年销售额：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"56\" style=\"word-break: break-all;\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"年销售额\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"100\" orgtype=\"text\" style=\"text-align: left; width: 100px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td width=\"89\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                <strong><span style=\"font-size: 14px;\">业务范围：</span></strong>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"162\">\n");
      out.write("                <input name=\"leipiNewField\" type=\"text\" title=\"义务范围\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"120\" orgtype=\"text\" style=\"text-align: left; width: 120px;\"/>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("    </tbody>\n");
      out.write("</table>\n");
      out.write("<p>\n");
      out.write("    <br/>\n");
      out.write("</p>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
