/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-10-03 05:19:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bank;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class guiyuan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"css/bootstrap-theme.min.css\"></script>\n");
      out.write("<script src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>柜员权限管理</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<p style=\"text-align: left;\">\n");
      out.write("    <span style=\"font-size: 20px;\">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span style=\"font-size: 24px;\"> 用户信息</span></span>\n");
      out.write("</p>\n");
      out.write("<table data-sort=\"sortDisabled\">\n");
      out.write("    <tbody>\n");
      out.write("        <tr class=\"firstRow\">\n");
      out.write("            <td width=\"88\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                角色类别\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"4\">\n");
      out.write("                <span leipiplugins=\"select\"><select name=\"leipiNewField\" title=\"ROLE_ID\" id=\"ROLE_ID\" leipiplugins=\"select\" size=\"1\" orgwidth=\"150\" style=\"width: 150px;\"><option value=\"1\">\n");
      out.write("                    1\n");
      out.write("                </option>\n");
      out.write("                <option value=\"2\">\n");
      out.write("                    2\n");
      out.write("                </option>\n");
      out.write("                <option value=\"3\">\n");
      out.write("                    3\n");
      out.write("                </option></select>&nbsp;&nbsp;</span>\n");
      out.write("            </td>\n");
      out.write("            <td width=\"84\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                姓名\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\">\n");
      out.write("                <input id=\"USER_NAME\" name=\"leipiNewField\" type=\"text\" title=\"USER_NAME\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"150\" orgtype=\"text\" style=\"text-align: left; width: 150px;\"/>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"88\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                年龄\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"4\">\n");
      out.write("                <input id=\"USER_AGE\" name=\"leipiNewField\" type=\"text\" title=\"USER_AGE\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"150\" orgtype=\"text\" style=\"text-align: left; width: 150px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td width=\"84\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                性别&nbsp;\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" style=\"word-break: break-all;\">\n");
      out.write("                <span leipiplugins=\"select\"><select id=\"USER_SEX\" name=\"leipiNewField\" title=\"USER_SEX\" leipiplugins=\"select\" size=\"1\" orgwidth=\"150\" style=\"width: 150px;\"><option value=\"男\">\n");
      out.write("                    男\n");
      out.write("                </option>\n");
      out.write("                <option value=\"女\">\n");
      out.write("                    女\n");
      out.write("                </option></select></span>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"88\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                身份证号码\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"4\">\n");
      out.write("                <input id=\"USER_IDCARD\" name=\"leipiNewField\" type=\"text\" title=\"USER_IDCARD\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"150\" orgtype=\"text\" style=\"text-align: left; width: 150px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td width=\"84\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                手机号码\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\">\n");
      out.write("                <input id=\"USER_PHONE\"  name=\"leipiNewField\" type=\"text\" title=\"USER_PHONE\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"150\" orgtype=\"text\" style=\"text-align: left; width: 150px;\"/>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"88\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                通行号码<br/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"4\">\n");
      out.write("                <input id=\"USER_PASSWORD\" name=\"leipiNewField\" type=\"text\" title=\"USER_PASSWORD\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"150\" orgtype=\"text\" style=\"text-align: left; width: 150px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td width=\"84\" valign=\"top\">\n");
      out.write("                城市<br/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\">\n");
      out.write("                <input id=\"USER_CITY\" name=\"leipiNewField\" type=\"text\" title=\"USER_CITY\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"150\" orgtype=\"text\" style=\"text-align: left; width: 150px;\"/>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td width=\"88\" valign=\"top\">\n");
      out.write("                详细地址<br/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\" width=\"4\">\n");
      out.write("                <input id=\"USER_ADDRESS\" name=\"leipiNewField\" type=\"text\" title=\"USER_ADDRESS\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"150\" orgtype=\"text\" style=\"text-align: left; width: 150px;\"/>\n");
      out.write("            </td>\n");
      out.write("            <td width=\"84\" valign=\"top\" style=\"word-break: break-all;\">\n");
      out.write("                状态<br/>\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" rowspan=\"1\" colspan=\"2\">\n");
      out.write("                <span leipiplugins=\"select\"><select id=\"USER_STATUS\" name=\"leipiNewField\" title=\"USER_STATUS\" leipiplugins=\"select\" size=\"1\" orgwidth=\"150\" style=\"width: 150px;\"><option value=\"0\">\n");
      out.write("                    正常\n");
      out.write("                </option>\n");
      out.write("                <option value=\"1\">\n");
      out.write("                    冻结\n");
      out.write("                </option></select>&nbsp;&nbsp;</span>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td valign=\"top\" colspan=\"1\" rowspan=\"1\" style=\"word-break: break-all;\">\n");
      out.write("                网络号\n");
      out.write("            </td>\n");
      out.write("            <td valign=\"top\" colspan=\"5\" rowspan=\"1\">\n");
      out.write("                <input id=\"NET\" name=\"leipiNewField\" type=\"text\" title=\"NET\" value=\"\" leipiplugins=\"text\" orghide=\"0\" orgalign=\"left\" orgwidth=\"150\" orgtype=\"text\" style=\"text-align: left; width: 150px;\"/>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("    </tbody>\n");
      out.write("</table>\n");
      out.write("<button id=\"submit\"> 提交</button>\n");
      out.write("<p style=\"text-align: center;\">\n");
      out.write("    <br/>\n");
      out.write("</p>\n");
      out.write("<p>\n");
      out.write("    <br/>\n");
      out.write("</p>\n");
      out.write("<p>\n");
      out.write("    <br/>\n");
      out.write("</p>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\t$('#submit').click(function(){\n");
      out.write("\t\t\n");
      out.write("\t\tvar object = {\n");
      out.write("\t\t\t\tROLE_ID:$(\"#ROLE_ID\").val(),\n");
      out.write("\t\t\t\tUSER_NAME:$(\"#USER_NAME\").val(),\n");
      out.write("\t\t\t\tUSER_SEX:$(\"#USER_SEX\").val(),\n");
      out.write("\t\t\t\tUSER_AGE:$(\"#USER_AGE\").val(),\n");
      out.write("\t\t\t\tUSER_IDCARD:$(\"#USER_IDCARD\").val(),\n");
      out.write("\t\t\t    USER_PHONE:$(\"#USER_PHONE\").val(),\n");
      out.write("\t\t\t    USER_PASSWORD:$(\"#USER_PASSWORD\").val(),\n");
      out.write("\t\t\t    USER_CITY:$(\"#USER_CITY\").val(),\n");
      out.write("\t\t\t    USER_ADDRESS:$(\"#USER_ADDRESS\").val(),\n");
      out.write("\t\t\t    USER_STATUS:$(\"#USER_STATUS\").val(), \n");
      out.write("\t\t\t    NET:$(\"#NET\").val(),\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t};\n");
      out.write("\t\t\n");
      out.write("\t    $.ajax({\n");
      out.write("\t        cache:true,//保留缓存数据\n");
      out.write("\t        type:\"post\",//为post请求\n");
      out.write("\t        url:\"Guiyuan\",//这是我在后台接受数据的文件名\n");
      out.write("\t       // data:$('#loginForm').serialize(),//将该表单序列化\n");
      out.write("\t       data:object,\n");
      out.write("\t       dataType:'json',\n");
      out.write("\t        async:false,//设置成true，这标志着在请求开始后，其他代码依然能够执行。如果把这个选项设置成false，这意味着所有的请求都不再是异步的了，这也会导致浏览器被锁死\n");
      out.write("\t        error:function(request){//请求失败之后的操作\n");
      out.write("\t            alert(\"系统繁忙，请稍候再试！\");\n");
      out.write("\t        },\n");
      out.write("\t        success:function(data){//请求成功之后的操作 \n");
      out.write("\n");
      out.write("\t        \t \n");
      out.write("\t        \t if(data.msg==\"1\"){\n");
      out.write("\t        \t\t alert(\"申请贷款成功！\");\n");
      out.write("\t        \t\t //$(\"#userid\").attr(\"value\",data.userid);\n");
      out.write("\t        \t }\n");
      out.write("\t        \t\t \n");
      out.write("\t        \t\n");
      out.write("\t        \t      //   $(\"#content-wrapper\").html(data);\n");
      out.write("\t        \t//document.getElementById(\"str\").value=data.msg2;\n");
      out.write("\t        }\n");
      out.write("\t    });\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("</script> \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
