/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-09-29 02:16:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bank;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.zhoukan.bean.*;

public final class settleRec_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.zhoukan.bean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	SettleRecBean reMess = (SettleRecBean) request
			.getAttribute("SettleRecBean");
	if (reMess != null) {
		pageContext.setAttribute("reMess", reMess.getRecieveMess());
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<title>贷款回收结算</title>\r\n");
      out.write("\t\t<link href=\"../mages/css1/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"images/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"teller/css/form-field-tooltip.css\"  media=\"screen\" type=\"text/css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"teller/js/rounded-corners.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"teller/js/form-field-tooltip.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/TELLER2.0/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("function AjaxApi(){\r\n");
      out.write("  \r\n");
      out.write("  \t\tvar debug = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(debug)alert(\"new AjaxApi()\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.parameters = arguments;\t\t//参数列表\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.param = null;\t\t\t//请求参数\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.url = null;   \t\t\t//请求地址\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tAjaxApi.prototype.request = false;//Ajax 请求核心对象\r\n");
      out.write("\t\tAjaxApi.prototype.returnfunction = null; \r\n");
      out.write("\t\tAjaxApi.prototype.starfunction = null; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.intiEngine=function(){//初始化Ajax引擎\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tAjaxApi.prototype.request = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else if (window.ActiveXObject) { // IE浏览器\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\tAjaxApi.prototype.request = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\tAjaxApi.prototype.request = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\t\t} catch (e) {alert('初始化Ajax引擎失败！');}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.iniParams=function(){//初始化参数\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(this.parameters.length == 4){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tthis.url = this.parameters[0]\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tthis.param = this.parameters[1];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tAjaxApi.prototype.returnfunction = this.parameters[2];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tAjaxApi.prototype.starfunction = this.parameters[3];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.send=function(){//主方法\r\n");
      out.write("\t\t\tvar url2 = this.url + \"?\" + this.param;\r\n");
      out.write("\t\t\tthis.request.open(\"GET\", url2 ,true);\r\n");
      out.write("\t\t\tthis.request.onreadystatechange=this.onChange;\r\n");
      out.write("\t\t\tthis.request.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.onChange = function(){//调用方法\r\n");
      out.write("\t\t\tvar state = AjaxApi.prototype.request.readyState;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(state == 1){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif(AjaxApi.prototype.starfunction!=null){\r\n");
      out.write("\t\t\t\t\tAjaxApi.prototype.starfunction();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(state == 4){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif(AjaxApi.prototype.request.status==200){\r\n");
      out.write("\t\t\t\t\tvar xmlDoc = AjaxApi.prototype.request.responseXML;  \r\n");
      out.write("\t\t\t    \tAjaxApi.prototype.returnfunction(xmlDoc);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.intiEngine();//执行初始化\r\n");
      out.write("\t\tthis.iniParams();//\r\n");
      out.write("\t\t\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction messSend() {\r\n");
      out.write("\t\tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("\t\tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("\t\tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("\t\tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("\t\tsendMess.innerHTML = '正在执行......';\r\n");
      out.write("\t\trecieveMess.innerHTML = '';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction messRecieve(mess) {\r\n");
      out.write("\t\tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("\t\tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("\t\tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("\t\tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("\t\tif (mess == null || mess == undefined) {\r\n");
      out.write("\t\t\tmess = '0000';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsendMess.innerHTML = '执行完成';\r\n");
      out.write("\t\trecieveMess.innerHTML = mess;\r\n");
      out.write("\t\t//alert(1);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getReceiptMes(){\r\n");
      out.write("\tvar loan_no =document.getElementById('loan_no').value;\r\n");
      out.write("\tvar DEBIT_NOTE_NO=document.getElementById('DEBIT_NOTE_NO').value;\r\n");
      out.write("\tif(loan_no == null || loan_no ==''){\r\n");
      out.write("\t\talert('贷款号不能为空');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(DEBIT_NOTE_NO == null || DEBIT_NOTE_NO ==''){\r\n");
      out.write("\t\talert('通知号不能为空');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar ajax = new AjaxApi('getMessage.do', 'LOAN_NO7='+loan_no+'&DEBIT_NOTE_NO1='+DEBIT_NOTE_NO,doxml,messSend);\r\n");
      out.write("\t //actionmessage中配置，页面传值，执行完成的js,先开始时执行的\r\n");
      out.write("\t \t ajax.send();\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t function doxml(xml){\r\n");
      out.write("\t\t   messRecieve();\t\r\n");
      out.write("\t var ORIG_BORRPWER = xml.getElementsByTagName('ORIG_BORRPWER')[0].text;\t\r\n");
      out.write("\t var LENDER = xml.getElementsByTagName('LENDER')[0].text;\r\n");
      out.write("\t var INVOICE_TYPE = xml.getElementsByTagName('INVOICE_TYPE')[0].text;\r\n");
      out.write("\t var BILLED_AMT = xml.getElementsByTagName('BILLED_AMT')[0].text;\r\n");
      out.write("\t var ACCT_NO = xml.getElementsByTagName('ACCT_NO')[0].text;\r\n");
      out.write("\t var ACCT_AMT = xml.getElementsByTagName('ACCT_AMT')[0].text;\r\n");
      out.write("\t var CLIENT = xml.getElementsByTagName('CLIENT')[0].text;\r\n");
      out.write("\t var OTH_ACCT_NO = xml.getElementsByTagName('OTH_ACCT_NO')[0].text;\r\n");
      out.write("\t var OTH_ACCT_AMT = xml.getElementsByTagName('OTH_ACCT_AMT')[0].text;\r\n");
      out.write("\t var OTH_CLIENT = xml.getElementsByTagName('OTH_CLIENT')[0].text;\r\n");
      out.write("\t var OUTSTANDING = xml.getElementsByTagName('OUTSTANDING')[0].text;\r\n");
      out.write("\t var MONEY = xml.getElementsByTagName('MONEY')[0].text;\r\n");
      out.write("\t var OTH_MONEY = xml.getElementsByTagName('OTH_MONEY')[0].text;\r\n");
      out.write("\t document.getElementById('ORIG_BORRPWER').value = ORIG_BORRPWER;\r\n");
      out.write("\t document.getElementById('LENDER').value = LENDER;\r\n");
      out.write("\t document.getElementById('INVOICE_TYPE').value = INVOICE_TYPE;\r\n");
      out.write("\t document.getElementById('BILLED_AMT').value = BILLED_AMT;\r\n");
      out.write("\t document.getElementById('ACCT_NO').value = ACCT_NO;\r\n");
      out.write("\t document.getElementById('ACCT_AMT').value = ACCT_AMT;\r\n");
      out.write("\t document.getElementById('CLIENT').value = CLIENT;\r\n");
      out.write("\t document.getElementById('OTH_ACCT_NO').value = OTH_ACCT_NO;\r\n");
      out.write("\t document.getElementById('OTH_ACCT_AMT').value = OTH_ACCT_AMT;\r\n");
      out.write("\t document.getElementById('OTH_CLIENT').value = OTH_CLIENT;\r\n");
      out.write("\t document.getElementById('OUTSTANDING').value = OUTSTANDING;\r\n");
      out.write("\t document.getElementById('MONEY').value = MONEY;\r\n");
      out.write("\t document.getElementById('OTH_MONEY').value = OTH_MONEY;\r\n");
      out.write("\t \r\n");
      out.write("\t }\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<body onLoad=\"messRecieve(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.reMess }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\">\r\n");
      out.write("\t\t<form name=\"form1\" method=\"post\" action=\"settleRec.do\">\r\n");
      out.write("    <table width=\"100%\" height=\"31\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"left_topbg\" id=\"table2\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"31\"><div class=\"titlebt\">回收结算</div></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\t\t\t<table class=\"left_txt2\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr class=\"left_txt\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<th  height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t贷款信息\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t          <tr>\r\n");
      out.write("\t\t            <td height=\"20\"><table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("\t\t              <tr>\r\n");
      out.write("\t\t                <td></td>\r\n");
      out.write("\t\t              </tr>\r\n");
      out.write("\t\t            </table></td>\r\n");
      out.write("\t\t          </tr>\t\r\n");
      out.write("\t\t    </table>      \t\t\r\n");
      out.write("\t\t\t<table class=\"left_txt2\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"12%\" height=\"35\" align=\"right\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t通知单号：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"left_txt2\" width=\"38%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"DEBIT_NOTE_NO\" id=\"DEBIT_NOTE_NO\" type=\"text\" size=\"35\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"38\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.DEBIT_NOTE_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"12%\" align=\"right\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t贷款号：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"38%\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"LOAN_NO\" id=\"loan_no\" type=\"text\" size=\"35\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"38\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.LOAN_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"12%\" align=\"right\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t回收金额：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"38%\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"BILLED_AMT\" id=\"BILLED_AMT\" type=\"text\" size=\"35\" maxlength=\"38\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.BILLED_AMT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"12%\" align=\"right\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"38%\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" name=\"find\" value=\"查询\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"getReceiptMes()\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"12%\" height=\"35\" align=\"right\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t贷款人编号：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"left_txt2\" width=\"38%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"ORIG_BORRPWER\" name=\"ORIG_BORRPWER\" type=\"text\" size=\"35\" maxlength=\"38\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.ORIG_BORRPWER}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"12%\" align=\"right\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t贷款人姓名：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"38%\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"LENDER\" id=\"LENDER\" type=\"text\" size=\"35\" maxlength=\"38\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.LENDER}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"12%\" height=\"35\" align=\"right\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t金额类型：\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"left_txt2\" width=\"38%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"INVOICE_TYPE\" id=\"INVOICE_TYPE\" type=\"text\" size=\"35\" maxlength=\"38\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.INVOICE_TYPE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"12%\" align=\"right\" class=\"left_txt2\"> \r\n");
      out.write("\t\t\t\t\t\t\t应收未收金额： \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"38%\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"OUTSTANDING\" id=\"OUTSTANDING\" type=\"text\" size=\"35\" maxlength=\"38\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.OUTSTANDING}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table class=\"left_txt2\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr class=\"left_txt\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<th  height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t默认扣款账户信息\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t          <tr>\r\n");
      out.write("\t\t            <td height=\"20\"><table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("\t\t              <tr>\r\n");
      out.write("\t\t                <td></td>\r\n");
      out.write("\t\t              </tr>\r\n");
      out.write("\t\t            </table></td>\r\n");
      out.write("\t\t          </tr>\t\r\n");
      out.write("\t\t    </table>  \r\n");
      out.write("\t\t\t<table class=\"left_txt2\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t账户类型\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t结算方式\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"20%\" height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t结算账户\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t回收币种\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t帐户余额\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t回收金额\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t帐户持有人\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"select8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t1 活期\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2 定期\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"select9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t1 自动结算\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2 手动结算\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"ACCT_NO\" id=\"ACCT_NO\" type=\"text\" size=\"27\" maxlength=\"27\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.ACCT_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"select6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t1 人民币\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2 美元\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t3 欧元\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"ACCT_AMT\" id=\"ACCT_AMT\" type=\"text\" size=\"20\" maxlength=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.ACCT_AMT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"MONEY\" id=\"MONEY\" type=\"text\" size=\"20\" maxlength=\"20\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.MONEY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"CLIENT\" id=\"CLIENT\" type=\"text\" size=\"20\" maxlength=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.CLIENT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr></table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<table class=\"left_txt2\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr class=\"left_txt\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<th  height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t备用扣款账户信息\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t          <tr>\r\n");
      out.write("\t\t            <td height=\"20\"><table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("\t\t              <tr>\r\n");
      out.write("\t\t                <td></td>\r\n");
      out.write("\t\t              </tr>\r\n");
      out.write("\t\t            </table></td>\r\n");
      out.write("\t\t          </tr>\t\r\n");
      out.write("\t\t    </table>  \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table class=\"left_txt2\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"select8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t1 活期\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2 定期\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"select9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t1 自动结算\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2 手动结算\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"OTH_ACCT_NO\" id=\"OTH_ACCT_NO\" type=\"text\" size=\"27\" maxlength=\"27\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.OTH_ACCT_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"select6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t1 人民币\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2 美元\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t3 欧元\r\n");
      out.write("\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"OTH_ACCT_AMT\" id=\"OTH_ACCT_AMT\" type=\"text\" size=\"20\" maxlength=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.OTH_ACCT_AMT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"OTH_MONEY\" id=\"OTH_MONEY\" type=\"text\" size=\"20\" maxlength=\"20\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.OTH_MONEY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"OTH_CLIENT\" id=\"OTH_CLIENT\" type=\"text\" size=\"20\" maxlength=\"20\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.SettleRecBean.OTH_CLIENT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table width=\"99%\" height=\"50\" border=\"0\" align=\"center\"\r\n");
      out.write("\t\t\t\tcellpadding=\"0\" cellspacing=\"1\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"46%\" height=\"35\" align=\"right\" valign=\"bottom\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"Submit2\" value=\"提交\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"7%\" height=\"35\" align=\"center\" class=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t&quot;\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"46%\" height=\"35\" align=\"left\" valign=\"bottom\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"left_txt2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"reset\" name=\"reset\" value=\"取消\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
