/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-09-28 02:49:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.teller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.zhoukan.bean.*;

public final class accruals_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.zhoukan.bean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gbk");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
AccrualsBean reMess = (AccrualsBean)request.getAttribute("accrualsBean");
if(reMess != null){
	pageContext.setAttribute("reMess",reMess.getRecieveMess());
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("<title>利息计提调整</title>\r\n");
      out.write("<link href=\"../mages/css1/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!--  <script type=\"text/javascript\" src=\"/TELLER2.0/myjs/change.js\"> </script>--> \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function sele(){\r\n");
      out.write("  \tform2.action=\"getAccrualsMes.do\";\r\n");
      out.write("  \tform2.submit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function messSend(){\r\n");
      out.write("  \tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("  \tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("  \tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("  \tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("  \tsendMess.innerHTML='正在执行......';\r\n");
      out.write("  \trecieveMess.innerHTML='';\r\n");
      out.write("}\r\n");
      out.write("function messRecieve(mess){\r\n");
      out.write("\tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("  \tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("  \tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("  \tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("  \tif(mess == null || mess==undefined){\r\n");
      out.write("  \t\tmess='0000';\r\n");
      out.write("  \t}\r\n");
      out.write("  \tsendMess.innerHTML='执行完成';\r\n");
      out.write("  \trecieveMess.innerHTML=mess;\r\n");
      out.write("  \t//alert(1);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body onLoad=\"messRecieve(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.reMess }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\">\r\n");
      out.write("<form name=\"form2\" method=\"POST\" action=\"accruals.do\" onSubmit=\"return check();\">\r\n");
      out.write("\r\n");
      out.write("<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\" align=\"center\" \r\n");
      out.write("border=\"0\">\r\n");
      out.write("  <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th class=\"bg_tr\" align=\"center\" colspan=\"2\" height=\"25\"> 计提信息</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"43\">\r\n");
      out.write("      \r\n");
      out.write("          <label></label>\r\n");
      out.write("          <label>操作类型：\r\n");
      out.write("          <select name=\"select\" onChange=\"findACT(this.value)\">\r\n");
      out.write("            <option value='1'>1、查询</option>\r\n");
      out.write("            <option value='2'>2、修改</option>\r\n");
      out.write("          </select>\r\n");
      out.write("          </label>\r\n");
      out.write("          </td>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\">贷款号：\r\n");
      out.write("        <label>\r\n");
      out.write("        <input name=\"LOAN_NO\" type=\"text\" size=\"38\" maxlength=\"38\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.LOAN_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      </label></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"46\"><label>发放号：\r\n");
      out.write("          <input name=\"DD_NO\" type=\"text\" size=\"38\" maxlength=\"38\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.DD_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      </label></td>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\"><label id=findACT>\r\n");
      out.write("     \r\n");
      out.write("\t  <input type=\"submit\" name=\"Submit3\" value=\"查询\" onclick=\"sele();\"/>\r\n");
      out.write("              \r\n");
      out.write("      </label></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td  colspan=\"2\" class=\"td_bg\">&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\" align=\"center\" \r\n");
      out.write("border=\"0\">\r\n");
      out.write("  <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th class=\"bg_tr\" align=\"center\" colspan=\"2\" height=\"25\">账户信息</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"47\"><label>贷款人：\r\n");
      out.write("          <input name=\"LENDER\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.LENDER}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      </label></td>\r\n");
      out.write("      <td width=\"50%\" class=\"td_bg\"><label>贷款状态：\r\n");
      out.write("          <input name=\"STATUS\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.STATUS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      </label></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"46\"><label>合同金额：\r\n");
      out.write("      <input name=\"ORIG_LOAN_AMT\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.ORIG_LOAN_AMT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> </label></td>\r\n");
      out.write("\t\t  \r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\"><label>发放金额：\r\n");
      out.write("          <input name=\"DD_AMT\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.DD_AMT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      </label></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"42\"><label>未发放金额：\r\n");
      out.write("      <input name=\"NOT_FOND\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.NOT_FOND}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> </label></td>\r\n");
      out.write("\t\t  \r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"42\"><label>贷款类型：\r\n");
      out.write("      <input name=\"LOAN_TYPE\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.LOAN_TYPE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> </label>\r\n");
      out.write("      </td> \r\n");
      out.write("    </tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"42\"><label>贷款经办机构：\r\n");
      out.write("      <input name=\"BOOK_BRANCH\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.BOOK_BRANCH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> </label>\r\n");
      out.write("      </td> \r\n");
      out.write("\t\t  \r\n");
      out.write("       <td class=\"td_bg\" width=\"50%\" height=\"42\"><label>贷款子类型：\r\n");
      out.write("      <input name=\"LOAN_SUB_TYPE\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.LOAN_SUB_TYPE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> </label>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"38\"><label>交易时间：\r\n");
      out.write("          <input name=\"DD_DATE\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.DD_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      </label></td>\r\n");
      out.write("\t\t  \r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\"><label></label></td> \r\n");
      out.write("    </tr>\r\n");
      out.write("\t\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\" align=\"center\" \r\n");
      out.write("border=\"0\">\r\n");
      out.write("  <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th class=\"bg_tr\" align=\"center\" colspan=\"2\" height=\"30\">利息信息</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"39\"><label>应收利息：\r\n");
      out.write("          <input name=\"INTEREST_AMT\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.INTEREST_AMT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      </label></td>\r\n");
      out.write("      <td width=\"50%\" class=\"td_bg\"><label>应收罚息：\r\n");
      out.write("          <input name=\"PENALTY_AMT_PRI\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.PENALTY_AMT_PRI}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      </label></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"td_bg\" height=\"37\"><span class=\"TableRow2\">\r\n");
      out.write("        <label>应收复利：\r\n");
      out.write("        <input name=\"PENALTY_AMT_INT\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.PENALTY_AMT_INT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        </label>\r\n");
      out.write("      </span></td>\r\n");
      out.write("      <td class=\"td_bg\" height=\"37\"><span class=\"TableRow2\">\r\n");
      out.write("        <label>当前利率：\r\n");
      out.write("        <input name=\"INT_RATE\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.INT_RATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        </label>\r\n");
      out.write("      </span></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"td_bg\" height=\"37\"><span class=\"TableRow2\">\r\n");
      out.write("        <label>基准利率：\r\n");
      out.write("        <input name=\"INT_BASISRATE\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.INT_BASISRATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        </label>\r\n");
      out.write("      </span></td>\r\n");
      out.write("      <td class=\"td_bg\" height=\"37\"><span class=\"TableRow2\">\r\n");
      out.write("        <label>本金罚息率：\r\n");
      out.write("        <input name=\"PRI_PLTI_RATE\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.PRI_PLTI_RATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        </label>\r\n");
      out.write("      </span></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"td_bg\" height=\"37\"><span class=\"TableRow2\">\r\n");
      out.write("        <label>基准罚息率：\r\n");
      out.write("        <input name=\"PRI_PLTY_ABS\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.PRI_PLTY_ABS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        </label>\r\n");
      out.write("      </span></td>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"38\"><label>复利利率：\r\n");
      out.write("          <input name=\"INT_PITY_RATE\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.INT_PITY_RATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("      </label></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"td_bg\" height=\"37\"><span class=\"TableRow2\">\r\n");
      out.write("        <label>基准复利率：\r\n");
      out.write("        <input name=\"INT_PITY_ABS\" type=\"text\" size=\"40\" maxlength=\"40\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.accrualsBean.INT_PITY_ABS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        </label>\r\n");
      out.write("      </span></td>\r\n");
      out.write("      <td class=\"td_bg\" width=\"50%\" height=\"38\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\" align=\"center\" \r\n");
      out.write("border=\"0\">\r\n");
      out.write("  <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th height=\"53\" colspan=\"2\" align=\"center\" class=\"bg_tr\"><label></label>\r\n");
      out.write("      <label></label></th>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <td width=\"49%\" height=\"53\" align=\"center\" class=\"td_bg\"><label>\r\n");
      out.write("\t  <input type=\"submit\" name=\"Submit2\" value=\"提交\" onclick=\"messSend();\"/>\r\n");
      out.write("\t  </label></td>\r\n");
      out.write("      <td width=\"51%\" align=\"center\" class=\"td_bg\"><label>\r\n");
      out.write("      <input type=\"reset\" name=\"Submit3\" value=\"取消\">\r\n");
      out.write("      </label></td>\r\n");
      out.write("\t  \r\n");
      out.write("    </tr>\r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\" align=\"center\" \r\n");
      out.write("border=\"0\">\r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
