/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-09-21 05:41:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.teller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.zhoukan.bean.*;

public final class clientRegiste_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.zhoukan.bean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
ClientRegisterBean_TE reMess = (ClientRegisterBean_TE)request.getAttribute("clientBean");
if(reMess != null){
	pageContext.setAttribute("reMess",reMess.getRecieveMess());
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>客户开户</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\tbackground-color: #F8F9FA;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write(".must{color: red ;font-size: 20px; margin-top: 10px}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<link href=\"images/skin.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"teller/css/form-field-tooltip.css\"  media=\"screen\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"teller/js/rounded-corners.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"teller/js/form-field-tooltip.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write(" <!--  <script type=\"text/javascript\" src=\"/TELLER2.0/myjs/change.js\"> </script>--> \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function messSend(){\r\n");
      out.write("  \tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("  \tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("  \tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("  \tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("  \tsendMess.innerHTML='正在执行......';\r\n");
      out.write("  \trecieveMess.innerHTML='';\r\n");
      out.write("}\r\n");
      out.write("function messRecieve(mess){\r\n");
      out.write("\tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("  \tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("  \tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("  \tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("  \tif(mess == null || mess==undefined){\r\n");
      out.write("  \t\tmess='0000';\r\n");
      out.write("  \t}\r\n");
      out.write("  \tsendMess.innerHTML='执行完成';\r\n");
      out.write("  \trecieveMess.innerHTML=mess;\r\n");
      out.write("  \t//alert(1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function $(name){\r\n");
      out.write(" return document.getElementById(name).value;\r\n");
      out.write("}\r\n");
      out.write("function check(){\r\n");
      out.write("\tvar GLOBAL_ID =  $(\"GLOBAL_ID\");\r\n");
      out.write("\tif(GLOBAL_ID == null || GLOBAL_ID ==''){\r\n");
      out.write("\t\talert('证件号不能为空');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar glTxt =/^[0-9][0-9]{16}.{1}$/;\r\n");
      out.write("\tif(!glTxt.test(GLOBAL_ID)){\r\n");
      out.write("\t\talert('证件号格式不对！必须是18位');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar GLOBAL_ID_AGAIN = $(\"GLOBAL_ID_AGAIN\");\r\n");
      out.write("\tif(GLOBAL_ID_AGAIN != GLOBAL_ID){\r\n");
      out.write("\t\talert('两次输入证件号不一致！');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar CH_CLIENT_NAME = $(\"CH_CLIENT_NAME\");\r\n");
      out.write("\tif(CH_CLIENT_NAME == '' || CH_CLIENT_NAME == null){\r\n");
      out.write("\t\talert(\"中文名不能为空\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t var CLIENT_NAME = $(\"CLIENT_NAME\");\r\n");
      out.write("\tif(CLIENT_NAME == '' || CLIENT_NAME == null){\r\n");
      out.write("\t\talert(\"英文名不能为空！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t /*var tel_txt = /(^[a-z][A-Z]$/;\r\n");
      out.write("\tif(!tel_txt.test(CLIENT_NAME)){\r\n");
      out.write("\t\talert(\"英文名格式不对！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}*/\r\n");
      out.write("\t\r\n");
      out.write(" var CLIENT_TEL_TYPE = $(\"CLIENT_TEL_TYPE\");\r\n");
      out.write("\tif(CLIENT_TEL_TYPE == '' || CLIENT_TEL_TYPE == null){\r\n");
      out.write("\t\talert(\"联系方式不能为空！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t var CLIENT_PROVINCE = $(\"CLIENT_PROVINCE\");\r\n");
      out.write("\tif(CLIENT_PROVINCE == '' || CLIENT_PROVINCE == null){\r\n");
      out.write("\t\talert(\"省份不能为空！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar CLIENT_CITY = $(\"CLIENT_CITY\"); \r\n");
      out.write("\tif(CLIENT_CITY == '' || CLIENT_CITY == null){\r\n");
      out.write("\t\talert(\"城市不能为空！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar CLIENT_ADDR = $(\"CLIENT_ADDR\");\r\n");
      out.write("\tif(CLIENT_ADDR == '' || CLIENT_ADDR == null){\r\n");
      out.write("\t\talert(\"地址不能为空！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar CLIENT_TEL = $(\"CLIENT_TEL\");\r\n");
      out.write("\tif(CLIENT_TEL == '' || CLIENT_TEL == null){\r\n");
      out.write("\t\talert(\"电话不能为空！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar tel_txt = /(^[0-9][0-9]{3,4}[0-9]{8}$)|^[0-9]{11}/;\r\n");
      out.write("\tif(!tel_txt.test(CLIENT_TEL)){\r\n");
      out.write("\t\talert(\"电话格式不对！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar CLIENT_ADDR_ZONE_CODE = $(\"CLIENT_ADDR_ZONE_CODE\");\r\n");
      out.write("\tvar tel_txt = /(^[0-9]{3,4}$)/;\r\n");
      out.write("\tif(!tel_txt.test(CLIENT_ADDR_ZONE_CODE)){\r\n");
      out.write("\t\talert(\"地区区号格式不对，应该3-4位！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar CITY_POSTCODE = $(\"CITY_POSTCODE\");\r\n");
      out.write("\tvar tel_txt = /(^[0-9]{6}$)/;\r\n");
      out.write("\tif(!tel_txt.test(CITY_POSTCODE)){\r\n");
      out.write("\t\talert(\"邮编格式不对，应该6位数字！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar CLIENT_SHORT = $('CLIENT_SHORT');\r\n");
      out.write("\tif(CLIENT_SHORT == '' || CLIENT_SHORT == null){\r\n");
      out.write("\t\talert(\"客户简称不能为空！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar CLIENT_NO = $(\"CLIENT_NO\");\r\n");
      out.write("\tif(!(CLIENT_NO =='' || CLIENT_NO == null)){\r\n");
      out.write("\t\talert(\"客户号不能输入！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("  <body onLoad=\"messRecieve(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.reMess }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\">\r\n");
      out.write(" <form name=\"form1\" method=\"POST\" action=\"clientRegister.do\" onSubmit=\"return check();\">\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"17\" height=\"29\" valign=\"top\" background=\"images/mail_leftbg.gif\"><img src=\"images/left-top-right.gif\" width=\"17\" height=\"29\" /></td>\r\n");
      out.write("    <td width=\"935\" height=\"29\" valign=\"top\" background=\"images/content-bg.gif\">\r\n");
      out.write("    <table width=\"100%\" height=\"31\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"left_topbg\" id=\"table2\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"31\"><div class=\"titlebt\">开户设置</div></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("    <td width=\"16\" valign=\"top\" background=\"images/mail_rightbg.gif\"><img src=\"images/nav-right-bg.gif\" width=\"16\" height=\"29\" /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"71\" valign=\"middle\" background=\"images/mail_leftbg.gif\">&nbsp;</td>\r\n");
      out.write("    <td valign=\"top\" bgcolor=\"#F7F8F9\">\r\n");
      out.write("    <table width=\"100%\" height= \"138\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"13\" valign=\"top\">&nbsp;</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td valign=\"top\"><table width=\"98%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class=\"left_txt\">当前位置：客户注册</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"20\"><table width=\"100%\" height=\"1\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#CCCCCC\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><table width=\"100%\" height=\"55\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"10%\" height=\"55\" valign=\"middle\"><img src=\"images/title.gif\" width=\"54\" height=\"55\"></td>\r\n");
      out.write("                <td width=\"90%\" valign=\"top\"><span class=\"left_txt2\">在这里，您可以根据\r\n");
      out.write("\t\t\t\t客户信息填入</span><span class=\"left_txt3\">基本参数</span><span class=\"left_txt2\">！</span><br>\r\n");
      out.write("                          <span class=\"left_txt2\">包括</span><span class=\"left_txt3\">用户编号，用户姓名，用户性别，用户住址，用户电话，用户家庭，用户年龄，备注，用户生日，卡号</span>\r\n");
      out.write("                          <span class=\"left_txt2\">以及卡密码</span><span class=\"left_txt3\">会员及等级积分设置</span><span class=\"left_txt2\">。 </span></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            <table width=\"100%\" height=\"31\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nowtable\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"left_bt2\">&nbsp;&nbsp;&nbsp;&nbsp;注册页面</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            \r\n");
      out.write("            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("<td><input name=\"OPER_ID\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginBean.USER_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("    \r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">客户编号：</td>\r\n");
      out.write("                <td height=\"30\"><input type=\"text\" name=\"CLIENT_NO\" size=\"30\"  readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CLIENT_NO }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></td>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">证件类型：</td>\r\n");
      out.write("                <td height=\"30\"><select name=\"GLOBAL_ID_TYPE\" style=\"width: 40%;\"> <option value=\"identity_card\" selected=\"selected\">身份证</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"military_card\">军人证</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"passport\">护照</option></select><a class=\"must\">*</a></td>\r\n");
      out.write("              </tr>\t\r\n");
      out.write("              \t\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\">证件号码：</td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"><input name=\"GLOBAL_ID\" type=\"text\" size=\"30\"   maxlength=\"18\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.GLOBAL_ID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" tooltipText=\"it must be a number\"/><a class=\"must\">*</a></td>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\">发证国家：</td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"><select name=\"COUNTRY_LICENCE\" style=\"width: 40%;\"> <option value=\"china\" selected=\"selected\">中国</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"USA\">美国</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Canada\">加拿大</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"England\">英国</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Italy\">意大利</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Japan\">日本</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Korea\">韩国</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Singapore\">新加坡</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t</select><a class=\"must\">*</a></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("                <tr>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">重新输入证件号：</td>\r\n");
      out.write("                <td height=\"30\"><input type=\"text\" name=\"GLOBAL_ID_AGAIN\" size=\"30\"  maxlength=\"18\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.GLOBAL_ID_AGAIN }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><a class=\"must\">*</a></td>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">性别：</td>\r\n");
      out.write("                <td height=\"30\"><select name=\"SEX\" style=\"width: 40%;\"> <option value=\"1\" selected=\"selected\">1 男</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"2\">2 女</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"3\">3 不详</option></select></td>\r\n");
      out.write("              </tr>\t\r\n");
      out.write("              \t\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\">客户类型：</td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"><select name=\"CATEGORY_TYPE\" style=\"width: 40%;\"> <option value=\"1\" selected=\"selected\">1 一般用户</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"2\">2 VIP</option></select><a class=\"must\">*</a></td>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\">客户分类：</td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"><select name=\"CLIENT_TYPE\" style=\"width: 40%;\"> <option value=\"1\" selected=\"selected\">1 贷款客户</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"2\">2 储蓄客户</option></select><a class=\"must\">*</a></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("                <tr>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">中文名：</td>\r\n");
      out.write("                <td height=\"30\"><input type=\"text\" name=\"CH_CLIENT_NAME\" size=\"30\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CH_CLIENT_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><a class=\"must\">*</a></td>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">英文名：</td>\r\n");
      out.write("                <td height=\"30\"><input type=\"text\" name=\"CLIENT_NAME\" size=\"30\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CLIENT_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" tooltipText=\"it must be an Englishname\"/><a class=\"must\">*</a></td>\r\n");
      out.write("              </tr>\t\r\n");
      out.write("              \t\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\">联系方式：</td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"><input name=\"CLIENT_TEL_TYPE\" type=\"text\"  size=\"30\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CLIENT_TEL_TYPE }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><a class=\"must\">*</a></td>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\"></td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("                <tr>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">国家：</td>\r\n");
      out.write("                <td height=\"30\"><select name=\"COUNTRY_LOC\" style=\"width: 40%;\"> <option value=\"china\" selected=\"selected\">中国</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"USA\">美国</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Canada\">加拿大</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"England\">英国</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Italy\">意大利</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Japan\">日本</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Korea\">韩国</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t<option value=\"Singapore\">新加坡</option>\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t\t\t\t</select><a class=\"must\">*</a></td>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">省份：</td>\r\n");
      out.write("                <td height=\"30\"><input type=\"text\" name=\"CLIENT_PROVINCE\" size=\"30\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CLIENT_PROVINCE }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><a class=\"must\">*</a></td>\r\n");
      out.write("              </tr>\t\r\n");
      out.write("              \t\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\">城市：</td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"><input name=\"CLIENT_CITY\" type=\"text\"  size=\"30\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CLIENT_CITY }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><a class=\"must\">*</a></td>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\">邮编：</td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"><input name=\"CITY_POSTCODE\" type=\"text\"   value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CITY_POSTCODE }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"size=\"30\" /></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("                <tr>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">地址信息：</td>\r\n");
      out.write("                <td height=\"30\"><input type=\"text\" name=\"CLIENT_ADDR\" size=\"30\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CLIENT_TEL_TYPE }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><a class=\"must\">*</a></td>\r\n");
      out.write("                <td height=\"30\" align=\"right\" class=\"left_txt2\">地区号码：</td>\r\n");
      out.write("                <td height=\"30\"><input type=\"text\" name=\"CLIENT_ADDR_ZONE_CODE\" size=\"30\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CLIENT_ADDR_ZONE_CODE }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  maxlength=\"8\" tooltipText=\"it must be a number\"/></td>\r\n");
      out.write("              </tr>\t\r\n");
      out.write("              \t\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\">电话：</td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"><input name=\"CLIENT_TEL\" type=\"text\"  size=\"30\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CLIENT_TEL }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"11\" tooltipText=\"it must be a number\"/><a class=\"must\">*</a></td>\r\n");
      out.write("                <td width=\"15%\" height=\"30\" align=\"right\" bgcolor=\"#f2f2f2\" class=\"left_txt2\">客户简称：</td>\r\n");
      out.write("                <td width=\"35%\" height=\"30\" bgcolor=\"#f2f2f2\"><input name=\"CLIENT_SHORT\" type=\"text\"  size=\"30\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.clientBean.CLIENT_SHORT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"50\"/><a class=\"must\">*</a></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("                 \r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"17\" colspan=\"4\" align=\"right\" >&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"30\" colspan=\"4\" align=\"right\" class=\"left_txt2\"><table width=\"100%\" height=\"31\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nowtable\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td class=\"left_bt2\">&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("        \r\n");
      out.write("            </table>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("          <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"50%\" height=\"30\" align=\"right\"><input type=\"submit\" value=\"提交\"  onclick=\"messSend();\"/></td>\r\n");
      out.write("              <td width=\"6%\" height=\"30\" align=\"right\">&nbsp;</td>\r\n");
      out.write("              <td width=\"44%\" height=\"30\"><input type=\"reset\" value=\"取消\"  /></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td height=\"30\" colspan=\"3\">&nbsp;</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("     \r\n");
      out.write("    </table></td>\r\n");
      out.write("   \r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write(" </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var tooltipObj = new DHTMLgoodies_formTooltip();\r\n");
      out.write("tooltipObj.setTooltipPosition('right');\r\n");
      out.write("tooltipObj.setPageBgColor('#f2f2f2');\r\n");
      out.write("tooltipObj.setTooltipCornerSize(10);\r\n");
      out.write("tooltipObj.initFormFieldTooltip();\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
