/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-09-28 02:49:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.teller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.zhoukan.bean.*;

public final class invoice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.zhoukan.bean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	InvoiceBean reMess = (InvoiceBean) request
			.getAttribute("invoiceBean");
	if (reMess != null) {
		pageContext.setAttribute("reMess", reMess.getRecieveMess());
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<title>本息通知单</title>\r\n");
      out.write("\t\t<link href=\"../mages/css1/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  \t  function getInvoice(){ \r\n");
      out.write("\t\tvar DD_NO5=document.getElementById('dd_no5').value;\r\n");
      out.write("\t\tvar LOAN_NO5=document.getElementById('loan_no5').value;\r\n");
      out.write("     \t\r\n");
      out.write("    if(DD_NO5 == '' || DD_NO5 == null){\r\n");
      out.write("\t\talert('发放号不能为空！');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("     \t}\r\n");
      out.write("    if(LOAN_NO5 == '' || LOAN_NO5 == null){\r\n");
      out.write("\t\talert('贷款号不能为空！');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("     \t}\r\n");
      out.write("\t //ajax\r\n");
      out.write("\t var ajax = new AjaxApi('getMessage.do', 'LOAN_NO5='+LOAN_NO5+'&DD_NO5='+DD_NO5,doxml,messSend);\r\n");
      out.write("\t //actionmessage中配置，页面传值，执行完成的js,先开始时执行的\r\n");
      out.write("\t \t ajax.send();\r\n");
      out.write("\t\t\r\n");
      out.write("\t //执行\r\n");
      out.write("\t  }\r\n");
      out.write("          function getFrontInvoice()\r\n");
      out.write("         {\r\n");
      out.write("            var DD_NO51=document.getElementById('dd_no').value;\r\n");
      out.write("\t\t    var LOAN_NO51=document.getElementById('loan_no').value;\r\n");
      out.write("            var INVOICE_TYPE=document.getElementById('invoice_type').value;\r\n");
      out.write("    if(INVOICE_TYPE == '' || INVOICE_TYPE == null){\r\n");
      out.write("\t\talert('发放号不能为空！');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("     \t}\r\n");
      out.write("    if(DD_NO51 == '' || DD_NO51 == null){\r\n");
      out.write("\t\talert('发放号不能为空！');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("     \t}\r\n");
      out.write("    if(LOAN_NO51 == '' || LOAN_NO51 == null){\r\n");
      out.write("\t\talert('贷款号不能为空！');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("     \t}\r\n");
      out.write("\t //ajax\r\n");
      out.write("\t var ajax = new AjaxApi('getMessage.do', 'LOAN_NO51='+LOAN_NO51+'&DD_NO51='+DD_NO51+'&INVOICE_TYPE='+INVOICE_TYPE,doxml1,messSend);\r\n");
      out.write("\t //actionmessage中配置，页面传值，执行完成的js,先开始时执行的\r\n");
      out.write("\t \t ajax.send();\r\n");
      out.write("\t\t\r\n");
      out.write("\t //执行\r\n");
      out.write("         }\r\n");
      out.write("          function doxml1(xml){\r\n");
      out.write("         messRecieve();\t\r\n");
      out.write("\t    // var LOAN_NO = xml.getElementsByTagName('LOAN_NO51')[0].text;\t\r\n");
      out.write("\t    // var DD_NO = xml.getElementsByTagName('DD_NO51')[0].text;\r\n");
      out.write("         var INT_RATE = xml.getElementsByTagName('INT_RATE')[0].text;\r\n");
      out.write("         var DUE_DATE = xml.getElementsByTagName('DUE_DATE')[0].text;\r\n");
      out.write("         var INT_FROM = xml.getElementsByTagName('INT_FROM')[0].text;\r\n");
      out.write("         var BILLED_AMT = xml.getElementsByTagName('BILLED_AMT')[0].text;\r\n");
      out.write("\t    // document.getElementById('LOAN_NO').value = LOAN_NO;\r\n");
      out.write("\t    // document.getElementById('DD_NO').value = DD_NO;\r\n");
      out.write("         document.getElementById('INT_RATE').value = INT_RATE;\r\n");
      out.write("         document.getElementById('DUE_DATE').value = DUE_DATE;\r\n");
      out.write("         document.getElementById('INT_FROM').value = INT_FROM;\r\n");
      out.write("         document.getElementById('BILLED_AMT').value = BILLED_AMT;\r\n");
      out.write("\t \r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function tgValue(xml,tgName){\r\n");
      out.write("\t \tvar val = xml.getElementsByTagName(tgName)[0];\r\n");
      out.write("\t \tif(val == '' || val == null){\r\n");
      out.write("\t \t\treturn '';\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \treturn val.text;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t  function doxml(xml){\r\n");
      out.write("      var txt,xx,x,i;\r\n");
      out.write("      messRecieve();\t\r\n");
      out.write("\t  x=xml.documentElement.getElementsByTagName(\"Invoice\");\r\n");
      out.write("      var tab=document.getElementById('txtInvoiceInfo');\r\n");
      out.write("      for (i=0;i<x.length;i++)\r\n");
      out.write("      {\r\n");
      out.write("      var newTr =tab.insertRow();\r\n");
      out.write("      var newTd1 = newTr.insertCell();\r\n");
      out.write("      xx=x[i].getElementsByTagName(\"DEBIT_NOTE_NO\");\r\n");
      out.write("      newTd1.innerHTML = \"<input type='text' value='\"+xx[0].firstChild.nodeValue+\"'/>\";\r\n");
      out.write("      \r\n");
      out.write("      var newTd2 = newTr.insertCell();  \r\n");
      out.write("      xx=x[i].getElementsByTagName(\"INVOICE_TYPE\");\r\n");
      out.write("      newTd2.innerHTML = \"<input type='text' value='\"+xx[0].firstChild.nodeValue+\"'/>\";\r\n");
      out.write("\r\n");
      out.write("      var newTd3 = newTr.insertCell();  \r\n");
      out.write("      xx=x[i].getElementsByTagName(\"INT_FROM\");\r\n");
      out.write("      newTd3.innerHTML = \"<input type='text' value='\"+xx[0].firstChild.nodeValue+\"'/>\";\r\n");
      out.write("        \r\n");
      out.write("      var newTd4 = newTr.insertCell();  \r\n");
      out.write("      xx=x[i].getElementsByTagName(\"DUE_DATE\");\r\n");
      out.write("      newTd4.innerHTML = \"<input type='text' value='\"+xx[0].firstChild.nodeValue+\"'/>\";\r\n");
      out.write("        \r\n");
      out.write("        var newTd5 = newTr.insertCell();  \r\n");
      out.write("      xx=x[i].getElementsByTagName(\"INT_RATE\");\r\n");
      out.write("      newTd5.innerHTML = \"<input type='text' value='\"+xx[0].firstChild.nodeValue+\"'/>\";\r\n");
      out.write("        \r\n");
      out.write("        var newTd6 = newTr.insertCell();  \r\n");
      out.write("      xx=x[i].getElementsByTagName(\"CCY\");\r\n");
      out.write("      newTd6.innerHTML = \"<input type='text' value='\"+xx[0].firstChild.nodeValue+\"'/>\";\r\n");
      out.write("        \r\n");
      out.write("        var newTd7 = newTr.insertCell();  \r\n");
      out.write("      xx=x[i].getElementsByTagName(\"BILLED_AMT\");\r\n");
      out.write("      newTd7.innerHTML = \"<input type='text' value='\"+xx[0].firstChild.nodeValue+\"'/>\";\r\n");
      out.write("      \r\n");
      out.write("      }\r\n");
      out.write("\t\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function tgValue(xml,tgName){\r\n");
      out.write("\t \tvar val = xml.getElementsByTagName(tgName)[0];\r\n");
      out.write("\t \tif(val == '' || val == null){\r\n");
      out.write("\t \t\treturn '';\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \treturn val.text;\r\n");
      out.write("\t}\r\n");
      out.write("  </script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("function AjaxApi(){\r\n");
      out.write("  \r\n");
      out.write("  \t\tvar debug = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(debug)alert(\"new AjaxApi()\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.parameters = arguments;\t\t//参数列表\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.param = null;\t\t\t//请求参数\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.url = null;   \t\t\t//请求地址\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tAjaxApi.prototype.request = false;//Ajax 请求核心对象\r\n");
      out.write("\t\tAjaxApi.prototype.returnfunction = null; \r\n");
      out.write("\t\tAjaxApi.prototype.starfunction = null; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.intiEngine=function(){//初始化Ajax引擎\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tAjaxApi.prototype.request = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else if (window.ActiveXObject) { // IE浏览器\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\tAjaxApi.prototype.request = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\tAjaxApi.prototype.request = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\t\t} catch (e) {alert('初始化Ajax引擎失败！');}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.iniParams=function(){//初始化参数\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(this.parameters.length == 4){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tthis.url = this.parameters[0]\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tthis.param = this.parameters[1];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tAjaxApi.prototype.returnfunction = this.parameters[2];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tAjaxApi.prototype.starfunction = this.parameters[3];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.send=function(){//主方法\r\n");
      out.write("\t\t\tvar url2 = this.url + \"?\" + this.param;\r\n");
      out.write("\t\t\tthis.request.open(\"GET\", url2 ,true);\r\n");
      out.write("\t\t\tthis.request.onreadystatechange=this.onChange;\r\n");
      out.write("\t\t\tthis.request.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.onChange = function(){//调用方法\r\n");
      out.write("\t\t\tvar state = AjaxApi.prototype.request.readyState;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(state == 1){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif(AjaxApi.prototype.starfunction!=null){\r\n");
      out.write("\t\t\t\t\tAjaxApi.prototype.starfunction();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(state == 4){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif(AjaxApi.prototype.request.status==200){\r\n");
      out.write("\t\t\t\t\tvar xmlDoc = AjaxApi.prototype.request.responseXML;  \r\n");
      out.write("\t\t\t    \tAjaxApi.prototype.returnfunction(xmlDoc);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.intiEngine();//执行初始化\r\n");
      out.write("\t\tthis.iniParams();//\r\n");
      out.write("\t\t\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\t<!--  <script type=\"text/javascript\" src=\"/TELLER2.0/myjs/change.js\"> </script>-->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("function sele() {\r\n");
      out.write("\tform2.action = \"getInvoiceMessage.do\";\r\n");
      out.write("\tform2.submit;\r\n");
      out.write("}\r\n");
      out.write("function messSend() {\r\n");
      out.write("\tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("\tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("\tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("\tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("\tsendMess.innerHTML = '正在执行......';\r\n");
      out.write("\trecieveMess.innerHTML = '';\r\n");
      out.write("}\r\n");
      out.write("function messRecieve(mess) {\r\n");
      out.write("\tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("\tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("\tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("\tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("\tif (mess == null || mess == undefined) {\r\n");
      out.write("\t\tmess = '0000';\r\n");
      out.write("\t}\r\n");
      out.write("\tsendMess.innerHTML = '执行完成';\r\n");
      out.write("\trecieveMess.innerHTML = mess;\r\n");
      out.write("\t//alert(1);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("function $(name) {\r\n");
      out.write("\treturn document.getElementById(name).value;\r\n");
      out.write("}\r\n");
      out.write("function check() {\r\n");
      out.write("\tvar GLOBAL_ID = $(\"GLOBAL_ID\");\r\n");
      out.write("\tif (GLOBAL_ID == null || GLOBAL_ID == '') {\r\n");
      out.write("\t\talert('证件号不能为空');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar glTxt = /^[0-9][0-9]{16}.{1}$/;\r\n");
      out.write("\tif (!glTxt.test(GLOBAL_ID)) {\r\n");
      out.write("\t\talert('证件号格式不对！必须是18位');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar GLOBAL_ID_AGAIN = $(\"GLOBAL_ID_AGAIN\");\r\n");
      out.write("\tif (GLOBAL_ID_AGAIN != GLOBAL_ID) {\r\n");
      out.write("\t\talert('两次输入证件号不一致！');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar CH_CLIENT_NAME = $(\"CH_CLIENT_NAME\");\r\n");
      out.write("\tif (CH_CLIENT_NAME == '' || CH_CLIENT_NAME == null) {\r\n");
      out.write("\t\talert(\"中文名不能为空\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar CLIENT_SHORT = $('CLIENT_SHORT');\r\n");
      out.write("\tif (CLIENT_SHORT == '' || CLIENT_SHORT == null) {\r\n");
      out.write("\t\talert(\"客户简称不能为空！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar CLIENT_NO = $(\"CLIENT_NO\");\r\n");
      out.write("\tif (!(CLIENT_NO == '' || CLIENT_NO == null)) {\r\n");
      out.write("\t\talert(\"客户号不能输入！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<SCRIPT language=javascript>\r\n");
      out.write("<!--\r\n");
      out.write("var displayBar=true;\r\n");
      out.write("function switchBar(obj){\r\n");
      out.write("\tif (displayBar)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tparent.frame.cols=\"0,*\";\r\n");
      out.write("\t\tdisplayBar=false;\r\n");
      out.write("\t\tobj.value=\"打开左边管理菜单\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tparent.frame.cols=\"195,*\";\r\n");
      out.write("\t\tdisplayBar=true;\r\n");
      out.write("\t\tobj.value=\"关闭左边管理菜单\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fullmenu(url){\r\n");
      out.write("\tif (url==null) {url = \"admin_left.asp\";}\r\n");
      out.write("\tparent.leftFrame.location = url;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\t<body onLoad=\"messRecieve(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.reMess }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\">\r\n");
      out.write("\t\t<form name=\"form1\" method=\"POST\" action=\"invoice.do\"\r\n");
      out.write("\t\t\tonSubmit=\"return check();\">\r\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"17\" height=\"29\" valign=\"top\"\r\n");
      out.write("\t\t\t\t\t\tbackground=\"images/mail_leftbg.gif\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/left-top-right.gif\" width=\"17\" height=\"29\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"935\" height=\"29\" valign=\"top\"\r\n");
      out.write("\t\t\t\t\t\tbackground=\"images/content-bg.gif\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\" height=\"31\" border=\"0\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\tcellspacing=\"0\" class=\"left_topbg\" id=\"table2\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"31\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"titlebt\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t本息通知单\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"16\" valign=\"top\" background=\"images/mail_rightbg.gif\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/nav-right-bg.gif\" width=\"16\" height=\"29\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th height=\"25\" colspan=\"2\" align=\"left\" bgcolor=\"#006633\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"bg_tr\">\r\n");
      out.write("\t\t\t\t\t\t\t出单\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"bg_tr\" align=\"center\" colspan=\"2\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t通知单信息\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t通知单号：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"DEBIT_NOTE_NO\" type=\"text\" size=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.invoiceBean.DEBIT_NOTE_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t贷 款 号：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"LOAN_NO\" type=\"text\" size=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.invoiceBean.LOAN_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t发 放 号：\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"DD_NO\" type=\"text\" size=\"40\" maxlength=\"40\"\r\n");
      out.write("                                                                        onblur=\"getFrontInvoice();\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.invoiceBean.DD_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t币 种 ：\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"CCY\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"RMB\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t人民币\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"￥\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t美元\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"RY\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t日元\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"PON\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t英镑\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t开始计息日：\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"INT_FROM\" size=\"40\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.invoiceBean.INT_FROM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t利 率：\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"INT_RATE\" type=\"text\" size=\"40\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.invoiceBean.INT_RATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t金额类型：\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"INVOICE_TYPE\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"PRL\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t本金\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"NT\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t利息\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"ODP\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t罚息\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"ODL\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t复利\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t到 期 日：\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"DUE_DATE\" size=\"40\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.invoiceBean.DUE_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t出单金额：\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"BILLED_AMT\" size=\"40\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.invoiceBean.BILLED_AMT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"bg_tr\" align=\"center\" colspan=\"2\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t通知单查询\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t发 放 号：\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"DD_NO5\" id=\"dd_no5\" type=\"text\" size=\"40\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.invoiceBean.DD_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t贷 款 号：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"LOAN_NO5\" id=\"loan_no5\" type=\"text\" size=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.invoiceBean.LOAN_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"50%\" height=\"30\" align=\"right\"><input type=\"button\" value=\"查询\"  onclick=\"getInvoice();\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"bg_tr\" align=\"center\" colspan=\"7\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t查询信息\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" height=\"35\" align=\"center\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t通知单号\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" height=\"35\" align=\"center\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t金额类型\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"15%\" height=\"35\" align=\"center\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t开始计息日\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"14%\" height=\"35\" align=\"center\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t终止日期\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"13%\" height=\"35\" align=\"center\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t利率（%）\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"13%\" height=\"35\" align=\"center\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t币种\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"14%\" height=\"35\" align=\"center\" class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t出单金额\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("                     <table id=\"txtInvoiceInfo\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\t        align=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"100%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"50%\" height=\"30\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"提交\" onclick=\"messSend();\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"50%\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"reset\" value=\"取消\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
