/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-09-21 01:54:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.teller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tld/menu.tld", Long.valueOf(1520501662000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fmenu_005fmenu_0026_005floginBean;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fmenu_005fchlidMenu_0026_005fuserName_005fmainMenu;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fmenu_005fmenu_0026_005floginBean = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fmenu_005fchlidMenu_0026_005fuserName_005fmainMenu = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fmenu_005fmenu_0026_005floginBean.release();
    _005fjspx_005ftagPool_005fmenu_005fchlidMenu_0026_005fuserName_005fmainMenu.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<title>管理页面</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/prototype.lite.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/moo.fx.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/moo.fx.pack.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont:12px Arial, Helvetica, sans-serif;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tbackground-color: #EEF2FB;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("}\r\n");
      out.write("#container {\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("}\r\n");
      out.write("H1 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("\tbackground-image: url(images/menu_bg.gif);\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tline-height: 20px;\t\r\n");
      out.write("}\r\n");
      out.write("H1 a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tmoz-outline-style: none;\r\n");
      out.write("\tbackground-image: url(images/menu_bgS.gif);\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write(".content{\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".MM ul {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write(".MM li {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 26px;\r\n");
      out.write("\tcolor: #333333;\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("\tpadding-left: 0px;\r\n");
      out.write("}\r\n");
      out.write(".MM {\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("\tright: 0px;\r\n");
      out.write("\tbottom: 0px;\r\n");
      out.write("\tclip: rect(0px,0px,0px,0px);\r\n");
      out.write("}\r\n");
      out.write(".MM a:link {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 26px;\r\n");
      out.write("\tcolor: #333333;\r\n");
      out.write("\tbackground-image: url(images/menu_bg1.gif);\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".MM a:visited {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 26px;\r\n");
      out.write("\tcolor: #333333;\r\n");
      out.write("\tbackground-image: url(images/menu_bg1.gif);\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".MM a:active {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 26px;\r\n");
      out.write("\tcolor: #333333;\r\n");
      out.write("\tbackground-image: url(images/menu_bg1.gif);\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".MM a:hover {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 26px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #006600;\r\n");
      out.write("\tbackground-image: url(images/menu_bg2.gif);\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\theight: 26px;\r\n");
      out.write("\twidth: 182px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\" height=\"280\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#EEF2FB\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"182\" valign=\"top\"><div id=\"container\">\r\n");
      out.write("    \r\n");
      out.write("      <!--  -->\r\n");
      out.write("      ");
      //  menu:menu
      org.zhoukan.bean.LoginBean LoginBean = null;
      org.zhoukan.tag.MenuTag _jspx_th_menu_005fmenu_005f0 = (org.zhoukan.tag.MenuTag) _005fjspx_005ftagPool_005fmenu_005fmenu_0026_005floginBean.get(org.zhoukan.tag.MenuTag.class);
      boolean _jspx_th_menu_005fmenu_005f0_reused = false;
      try {
        _jspx_th_menu_005fmenu_005f0.setPageContext(_jspx_page_context);
        _jspx_th_menu_005fmenu_005f0.setParent(null);
        // /teller/left.jsp(154,6) name = loginBean type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_menu_005fmenu_005f0.setLoginBean((org.zhoukan.bean.LoginBean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginBean}", org.zhoukan.bean.LoginBean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        int _jspx_eval_menu_005fmenu_005f0 = _jspx_th_menu_005fmenu_005f0.doStartTag();
        LoginBean = (org.zhoukan.bean.LoginBean) _jspx_page_context.findAttribute("LoginBean");
        if (_jspx_eval_menu_005fmenu_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      <h1 class=\"type\"><a href=\"javascript:void(0)\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.menuBean.POWER_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></h1>\r\n");
            out.write("      <div class=\"content\">\r\n");
            out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
            out.write("          <tr>\r\n");
            out.write("            <td><img src=\"images/menu_topline.gif\" width=\"182\" height=\"5\" /></td>\r\n");
            out.write("          </tr>\r\n");
            out.write("        </table>\r\n");
            out.write("        <ul class=\"MM\">\r\n");
            out.write("          ");
            //  menu:chlidMenu
            org.zhoukan.bean.MenuBean MenuBean = null;
            java.lang.String userName = null;
            org.zhoukan.tag.ChlidMenu _jspx_th_menu_005fchlidMenu_005f0 = (org.zhoukan.tag.ChlidMenu) _005fjspx_005ftagPool_005fmenu_005fchlidMenu_0026_005fuserName_005fmainMenu.get(org.zhoukan.tag.ChlidMenu.class);
            boolean _jspx_th_menu_005fchlidMenu_005f0_reused = false;
            try {
              _jspx_th_menu_005fchlidMenu_005f0.setPageContext(_jspx_page_context);
              _jspx_th_menu_005fchlidMenu_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_menu_005fmenu_005f0);
              // /teller/left.jsp(163,10) name = mainMenu type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_menu_005fchlidMenu_005f0.setMainMenu((org.zhoukan.bean.MenuBean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.menuBean}", org.zhoukan.bean.MenuBean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              // /teller/left.jsp(163,10) name = userName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_menu_005fchlidMenu_005f0.setUserName((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginBean.USER_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              int _jspx_eval_menu_005fchlidMenu_005f0 = _jspx_th_menu_005fchlidMenu_005f0.doStartTag();
              MenuBean = (org.zhoukan.bean.MenuBean) _jspx_page_context.findAttribute("MenuBean");
              userName = (java.lang.String) _jspx_page_context.findAttribute("userName");
              if (_jspx_eval_menu_005fchlidMenu_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("          <li><a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.chlidMenu.POWER_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("\" target=\"main\">");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.chlidMenu.POWER_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</a></li>\r\n");
                  out.write("          ");
                  int evalDoAfterBody = _jspx_th_menu_005fchlidMenu_005f0.doAfterBody();
                  MenuBean = (org.zhoukan.bean.MenuBean) _jspx_page_context.findAttribute("MenuBean");
                  userName = (java.lang.String) _jspx_page_context.findAttribute("userName");
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_menu_005fchlidMenu_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              MenuBean = (org.zhoukan.bean.MenuBean) _jspx_page_context.findAttribute("MenuBean");
              userName = (java.lang.String) _jspx_page_context.findAttribute("userName");
              _005fjspx_005ftagPool_005fmenu_005fchlidMenu_0026_005fuserName_005fmainMenu.reuse(_jspx_th_menu_005fchlidMenu_005f0);
              _jspx_th_menu_005fchlidMenu_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_menu_005fchlidMenu_005f0, _jsp_getInstanceManager(), _jspx_th_menu_005fchlidMenu_005f0_reused);
            }
            out.write("\r\n");
            out.write("        </ul>\r\n");
            out.write("      </div>\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_menu_005fmenu_005f0.doAfterBody();
            LoginBean = (org.zhoukan.bean.LoginBean) _jspx_page_context.findAttribute("LoginBean");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_menu_005fmenu_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        LoginBean = (org.zhoukan.bean.LoginBean) _jspx_page_context.findAttribute("LoginBean");
        _005fjspx_005ftagPool_005fmenu_005fmenu_0026_005floginBean.reuse(_jspx_th_menu_005fmenu_005f0);
        _jspx_th_menu_005fmenu_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_menu_005fmenu_005f0, _jsp_getInstanceManager(), _jspx_th_menu_005fmenu_005f0_reused);
      }
      out.write("\r\n");
      out.write("     <!--  -->\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("\t\tvar contents = document.getElementsByClassName('content');\r\n");
      out.write("\t\tvar toggles = document.getElementsByClassName('type');\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar myAccordion = new fx.Accordion(\r\n");
      out.write("\t\t\ttoggles, contents, {opacity: true, duration: 400}\r\n");
      out.write("\t\t);\r\n");
      out.write("\t\tmyAccordion.showThisHideOpen(contents[0]);\r\n");
      out.write("\t</script>\r\n");
      out.write("        </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
