/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-09-28 02:49:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.teller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.zhoukan.bean.*;

public final class openCurrentAcct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.zhoukan.bean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	OpenAccountBean reMess = (OpenAccountBean) request
			.getAttribute("openAccountBean");
	if (reMess != null) {
		pageContext.setAttribute("reMess", reMess.getRecieveMess());
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<title>账户开户</title>\r\n");
      out.write("\t\t<link href=\"../mages/css1/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/calendar.js\" ></script>  \r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/calendar-zh.js\" ></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/calendar-setup.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("function AjaxApi(){\r\n");
      out.write("  \r\n");
      out.write("  \t\tvar debug = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(debug)alert(\"new AjaxApi()\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.parameters = arguments;\t\t//参数列表\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.param = null;\t\t\t//请求参数\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.url = null;   \t\t\t//请求地址\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tAjaxApi.prototype.request = false;//Ajax 请求核心对象\r\n");
      out.write("\t\tAjaxApi.prototype.returnfunction = null; \r\n");
      out.write("\t\tAjaxApi.prototype.starfunction = null; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.intiEngine=function(){//初始化Ajax引擎\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tAjaxApi.prototype.request = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else if (window.ActiveXObject) { // IE浏览器\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\tAjaxApi.prototype.request = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\tAjaxApi.prototype.request = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\t\t} catch (e) {alert('初始化Ajax引擎失败！');}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.iniParams=function(){//初始化参数\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(this.parameters.length == 4){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tthis.url = this.parameters[0]\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tthis.param = this.parameters[1];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tAjaxApi.prototype.returnfunction = this.parameters[2];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tAjaxApi.prototype.starfunction = this.parameters[3];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.send=function(){//主方法\r\n");
      out.write("\t\t\tvar url2 = this.url + \"?\" + this.param;\r\n");
      out.write("\t\t\tthis.request.open(\"GET\", url2 ,true);\r\n");
      out.write("\t\t\tthis.request.onreadystatechange=this.onChange;\r\n");
      out.write("\t\t\tthis.request.send(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.onChange = function(){//调用方法\r\n");
      out.write("\t\t\tvar state = AjaxApi.prototype.request.readyState;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(state == 1){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif(AjaxApi.prototype.starfunction!=null){\r\n");
      out.write("\t\t\t\t\tAjaxApi.prototype.starfunction();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(state == 4){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif(AjaxApi.prototype.request.status==200){\r\n");
      out.write("\t\t\t\t\tvar xmlDoc = AjaxApi.prototype.request.responseXML;  \r\n");
      out.write("\t\t\t    \tAjaxApi.prototype.returnfunction(xmlDoc);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tthis.intiEngine();//执行初始化\r\n");
      out.write("\t\tthis.iniParams();//\r\n");
      out.write("\t\t\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\t<!--  <script type=\"text/javascript\" src=\"/TELLER2.0/myjs/change.js\"> </script>-->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("function Registe(){\r\n");
      out.write("\twindow.location.href=\"clientRegiste.jsp\";\r\n");
      out.write("}\r\n");
      out.write("function messSend(){\r\n");
      out.write("  \tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("  \tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("  \tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("  \tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("  \tsendMess.innerHTML='正在执行......';\r\n");
      out.write("  \trecieveMess.innerHTML='';\r\n");
      out.write("}\r\n");
      out.write("function messRecieve(mess){\r\n");
      out.write("\tvar frameBottom = parent.document.getElementById(\"messFrame\");\r\n");
      out.write("  \tvar messageWin = frameBottom.contentWindow;\r\n");
      out.write("  \tvar sendMess = messageWin.document.getElementById(\"sendMess\");\r\n");
      out.write("  \tvar recieveMess = messageWin.document.getElementById(\"recieveMess\");\r\n");
      out.write("  \tif(mess == null || mess==undefined){\r\n");
      out.write("  \t\tmess='0000';\r\n");
      out.write("  \t}\r\n");
      out.write("  \tsendMess.innerHTML='执行完成';\r\n");
      out.write("  \trecieveMess.innerHTML=mess;\r\n");
      out.write("  \t//alert(1);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("function $(name){\r\n");
      out.write(" return document.getElementById(name).value;\r\n");
      out.write("}\r\n");
      out.write("function check(){\r\n");
      out.write("\tvar GLOBAL_ID =  $(\"GLOBAL_ID\");\r\n");
      out.write("\tif(GLOBAL_ID == null || GLOBAL_ID ==''){\r\n");
      out.write("\t\talert('证件号不能为空');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar glTxt =/^[0-9][0-9]{16}.{1}$/;\r\n");
      out.write("\tif(!glTxt.test(GLOBAL_ID)){\r\n");
      out.write("\t\talert('证件号格式不对！必须是18位');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar GLOBAL_ID_AGAIN = $(\"GLOBAL_ID_AGAIN\");\r\n");
      out.write("\tif(GLOBAL_ID_AGAIN != GLOBAL_ID){\r\n");
      out.write("\t\talert('两次输入证件号不一致！');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar CH_CLIENT_NAME = $(\"CH_CLIENT_NAME\");\r\n");
      out.write("\tif(CH_CLIENT_NAME == '' || CH_CLIENT_NAME == null){\r\n");
      out.write("\t\talert(\"中文名不能为空\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\tvar CLIENT_SHORT = $('CLIENT_SHORT');\r\n");
      out.write("\tif(CLIENT_SHORT == '' || CLIENT_SHORT == null){\r\n");
      out.write("\t\talert(\"客户简称不能为空！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar CLIENT_NO = $(\"CLIENT_NO\");\r\n");
      out.write("\tif(!(CLIENT_NO =='' || CLIENT_NO == null)){\r\n");
      out.write("\t\talert(\"客户号不能输入！\");\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("  \t  function getClient(value){  \r\n");
      out.write("\t\t  var CLIENT_NO = value;\r\n");
      out.write("\tif(CLIENT_NO == '' || CLIENT_NO == null){\r\n");
      out.write("\t\talert('客户号不能为空！');\r\n");
      out.write("\t\tmessRecieve();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("     \t}\r\n");
      out.write("\t //ajax\r\n");
      out.write("\t var ajax = new AjaxApi('getMessage.do', 'CLIENT_NO='+CLIENT_NO,doxml,messSend);\r\n");
      out.write("\t //actionmessage中配置，页面传值，执行完成的js,先开始时执行的\r\n");
      out.write("\t \t ajax.send();\r\n");
      out.write("\t\t\r\n");
      out.write("\t //执行\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t  function doxml(xml){\r\n");
      out.write("\t\t   messRecieve();\t\r\n");
      out.write("\t var CLIENT_SHORT = xml.getElementsByTagName('CLIENT_SHORT')[0].text;\t\r\n");
      out.write("\t var GLOBAL_ID = xml.getElementsByTagName('GLOBAL_ID')[0].text;\r\n");
      out.write("\t document.getElementById('client_short').value = CLIENT_SHORT;\r\n");
      out.write("\t document.getElementById('global_id').value = GLOBAL_ID;\r\n");
      out.write("\t \r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function tgValue(xml,tgName){\r\n");
      out.write("\t \tvar val = xml.getElementsByTagName(tgName)[0];\r\n");
      out.write("\t \tif(val == '' || val == null){\r\n");
      out.write("\t \t\treturn '';\r\n");
      out.write("\t \t}\r\n");
      out.write("\t \treturn val.text;\r\n");
      out.write("\t}\r\n");
      out.write("  </script>\r\n");
      out.write("\t<body onLoad=\"messRecieve(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageScope.reMess }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\">\r\n");
      out.write("\t\t<form name=\"form1\" method=\"POST\" action=\"acctOpen.do\"\r\n");
      out.write("\t\t\tonSubmit=\"return check();\">\r\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th height=\"25\" colspan=\"2\" align=\"left\" bgcolor=\"#006633\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"bg_tr\">\r\n");
      out.write("\t\t\t\t\t\t\t活期账户页面\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"bg_tr\" align=\"center\" colspan=\"2\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t账号信息\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t账 号：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"BASE_ACCT_NO\" type=\"text\" size=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.BASE_ACCT_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t账户类型：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"ACCT_TYPE\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t个人\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t单位\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"must\">*</a>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t客户号：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"CLIENT_NO\" id=\"client_no\" type=\"text\" size=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"38\" onblur=\"getClient(this.value);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.CLIENT_NO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t证件类型：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"GLOBAL_ID_TYPE\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"identity_card\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t身份证\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"military_card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t军人证\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"passport\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t护照\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"must\">*</a>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"46\">\r\n");
      out.write("\t\t\t\t\t\t\t证件号码：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"GLOBAL_ID\" id=\"global_id\" type=\"text\" size=\"38\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmaxlength=\"38\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.GLOBAL_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"46\">\r\n");
      out.write("\t\t\t\t\t\t\t客户简称：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"CLIENT_SHORT\" id=\"client_short\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsize=\"38\" maxlength=\"38\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.CLIENT_SHORT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"50%\" align=\"center\" class=\"td_bg\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" name=\"Submit\" value=\"建立客户信息\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"Registe()\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table class=\"table\" cellspacing=\"1\" cellpadding=\"2\" width=\"99%\"\r\n");
      out.write("\t\t\t\talign=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"bg_tr\" align=\"center\" colspan=\"2\" height=\"25\">\r\n");
      out.write("\t\t\t\t\t\t\t账户明细\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t中文名：\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"CH_ACCT_NAME\" type=\"text\" size=\"40\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.CH_ACCT_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"50%\" class=\"td_bg\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t英文名：\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"ALT_ACCT_NAME\" type=\"text\" size=\"40\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.ALT_ACCT_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t客户类型：\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"CLIENT_TYPE\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"COM\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t普通客户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"VIP\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tVIP客户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"INT\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t银行员工\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t客户经理编号：\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"OFFICER_ID\" type=\"text\" size=\"40\" maxlength=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.OFFICER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t开户时间：<input type=\"text\" id=\"EntTime\" name=\"ACCT_OPEN_DATE\" onclick=\"return showCalendar('EntTime', 'y-mm-dd');\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.openAccountBean.ACCT_OPEN_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t账户状态：\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"ACCT_STATUS\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"A\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t活动\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"B\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t销户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"C\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t睡眠户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"D\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t充公户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"E\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t不活动\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"F\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t新建\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"G\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t已清除\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"H\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t待激活\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t账户币种：\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"CCY\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"CNY\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t人民币\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"MY\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t美元\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"RY\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t日元\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"PON\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t英镑\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t余额类型：\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"ACTUAL_OR_LEDGER_BAL\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"A\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t可用\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"L\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t账面\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t支取方式：\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"STMT_PBK\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"P\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t存折\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"S\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t对照单\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t<label></label>\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t账户属性：\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"ACCT_NATURE\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"B\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t基本户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"C\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t一般户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"S\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t专用户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"T\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t临时户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\" height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t账户限制标志：\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"RESTRAINT_PRESENT\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"N\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t否\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Y\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t是\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"td_bg\" width=\"50%\">\r\n");
      out.write("\t\t\t\t\t\t\t<label></label>\r\n");
      out.write("\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t存款类型：\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"DEPOSIT_TYPE\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"T\" selected=\"selected\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t定期账户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"C\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t往来账户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"S\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t储蓄账户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"A\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tAIO账户\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"50%\" height=\"30\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"提交\" onclick=\"messSend();\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"50%\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"reset\" value=\"取消\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
